src/Entity/Inscription.php
<?php

namespace App\Entity;

use App\Repository\InscriptionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InscriptionRepository::class)]
class Inscription
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 254)]
    private ?string $prenom = null;

    #[ORM\Column(length: 254)]
    private ?string $nom = null;

    #[ORM\Column(length: 254)]
    private ?string $email = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_insc = null;

    #[ORM\Column(length: 254, nullable: true)]
    private ?string $etablissement = null;

    #[ORM\Column(length: 254, nullable: true)]
    private ?string $annotation = null;

    #[ORM\ManyToOne(inversedBy: 'inscriptions')]
    private ?Sujet $sujet = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getDateInsc(): ?\DateTimeInterface
    {
        return $this->date_insc;
    }

    public function setDateInsc(\DateTimeInterface $date_insc): static
    {
        $this->date_insc = $date_insc;

        return $this;
    }

    public function getEtablissement(): ?string
    {
        return $this->etablissement;
    }

    public function setEtablissement(?string $etablissement): static
    {
        $this->etablissement = $etablissement;

        return $this;
    }

    public function getAnnotation(): ?string
    {
        return $this->annotation;
    }

    public function setAnnotation(?string $annotation): static
    {
        $this->annotation = $annotation;

        return $this;
    }

    public function getSujet(): ?Sujet
    {
        return $this->sujet;
    }

    public function setSujet(?Sujet $sujet): static
    {
        $this->sujet = $sujet;

        return $this;
    }
}

src/Form/InscriptionType.php
<?php

namespace App\Form;

use App\Entity\Inscription;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InscriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('prenom', TextType::class)
            ->add('nom', TextType::class)
            ->add('email', EmailType::class)
            ->add('etablissement')
            ->add('annotation', TextareaType::class, ['required' => false])
            ->add('enregistrer', SubmitType::class, [
                'label' => 'Enregistrer'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Inscription::class,
        ]);
    }
}

src/Controller/InscriptionController.php
<?php

namespace App\Controller;

use App\Entity\InfosResp;
use App\Entity\Inscription;
use App\Entity\Sujet;
use App\Entity\User;
use App\Form\InscriptionType;
use App\Service\Helpers;
use App\Service\MailerService;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class InscriptionController extends AbstractController
{
    #[
        Route('/inscription/delete/{id}', name: 'app_inscription_delete'),
        IsGranted('ROLE_ENSEIGNANT')
    ]
    public function delete(Request $request, ManagerRegistry $doctrine, Inscription $inscription = null): RedirectResponse
    {
        if ($inscription) {
            # Suppression de l'inscription
            $manager = $doctrine->getManager();
            $manager->remove($inscription);
            $manager->flush();
        }
        return $this->redirect($request->headers->get('referer'));
    }

    #[
        Route('/inscription/list/{id}', name: 'app_inscription_list'),
        IsGranted('ROLE_ENSEIGNANT')
    ]
    public function list(Sujet $sujet): Response
    {
        return $this->render('inscription/list_inscription.html.twig', [
            'controller_name' => 'SujetController',
            'data' => $sujet->getInscriptions(),
            'sujet_id' => $sujet->getId()
        ]);
    }

    #[
        Route('/inscription/{id_sujet}/{id_insc}', name: 'app_inscription_edit'),
        IsGranted('ROLE_ENSEIGNANT')
    ]
    public function edit(Request $request, EntityManagerInterface $em, int $id_sujet, int $id_insc): Response
    {
        # Récupération du sujet pour page de redirection
        $sujet = $em->getRepository(Sujet::class)->find($id_sujet);
        # Récupération de l'inscription pour le formulaire
        $insc = $em->getRepository(Inscription::class)->find($id_insc);

        $form = $this->createForm(InscriptionType::class, $insc);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($insc);
            $em->flush();
            $this->addFlash('success', "Inscription enregistrée avec succès.");

            return $this->redirectToRoute('app_inscription_list', ['id' => $sujet->getId()]);
        }

        return $this->render('inscription/index.html.twig', [
            'controller_name' => 'InscriptionController',
            'inscriptionForm' => $form->createView(),
            'sujet_title' => $sujet->getTitreSujet(),
        ]);
    }

    #[
        Route('/inscription/{id}/{prenom?}/{nom?}/{email?}/{etablissement?}', name: 'app_inscription'),
        IsGranted('ROLE_ENSEIGNANT')
    ]
    # Les paramètres sont récupérés depuis le lien passé dans l'e-mail du responsable
    public function index(Request $request, EntityManagerInterface $em, MailerService $mailer, Helpers $helpers,
                          Sujet $sujet, $prenom, $nom, $email, $etablissement): Response
    {
        $insc = new Inscription();
        $form = $this->createForm(InscriptionType::class, $insc);

        #Préremplissage du formulaire
        $form->get('prenom')->setData($prenom);
        $form->get('nom')->setData($nom);
        $form->get('email')->setData($email);
        $form->get('etablissement')->setData($etablissement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            # Création de l'inscription
            $insc->setDateInsc(new \DateTime());
            $insc->setSujet($sujet);
            $em->persist($insc);
            $em->flush();

            $this->addFlash('success', "Inscription enregistrée avec succès.");

            $user = $this->getUser();
            if ($user instanceof User){
                $infoResp = $helpers->getInfosRespFromUser($user);
            } else {
                $this->addFlash('error', "Erreur dans l'envoi du mail de confirmation (données de compte.");
                $this->redirectToRoute('app_home');
            }

            # Envoi du mail de confirmation à l'inscrit
            try {
                $mailer->sendInscConfirmationMail(
                    new Address($form->getData()->getEmail()),
                    [
                        'sujet_title' => $sujet->getTitreSujet(),
                        'prenom' => $infoResp->getPrenom(),
                        'nom' => $infoResp->getNom(),
                        'respo_mail' => $infoResp->getEmail(),
                    ]
                );
            } catch (TransportExceptionInterface $e) {
                $this->addFlash('error', "Erreur dans l'envoi du mail de confirmation.");
                $this->redirectToRoute('app_home');
            }

            return $this->redirectToRoute('app_home');
        }

        return $this->render('inscription/index.html.twig', [
            'controller_name' => 'InscriptionController',
            'inscriptionForm' => $form->createView(),
            'sujet_title' => $sujet->getTitreSujet(),
        ]);
    }
}

templates/inscription/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello InscriptionController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/guyot/PhpstormProjects/PCarre/src/Controller/InscriptionController.php'|file_link(0) }}">src/Controller/InscriptionController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/guyot/PhpstormProjects/PCarre/templates/inscription/index.html.twig'|file_link(0) }}">templates/inscription/index.html.twig</a></code></li>
    </ul>

    <div class="m-1">
        <h1>Formulaire d'inscription</h1>
        <h2>Sujet: {{ sujet_title }}</h2>

        {{ form(inscriptionForm) }}
    </div>
</div>
{% endblock %}

templates/inscription/list_inscription.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello InscriptionController!{% endblock %}

{% block javascripts %}
{#    {{ encore_entry_script_tags('insc_list') }}#}
{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">

        {# read and display just one flash message type #}
        {% for message in app.flashes('success') %}
            <div class="flash-notice text-success">
                {{ message }}
            </div>
        {% endfor %}

        <a href="{{ path('app_inscription', {id: sujet_id}) }}" class="btn btn-primary ml-5">Ajouter une inscription à ce sujet</a>

    </div>

    <div class="container">
        <div class="row">
            <div class="table-responsive small">
                <table class="table table-striped table-sm" id="example">
                    <thead>
                    <tr>
                        <th scope="col">Nom</th>
                        <th scope="col">E-mail</th>
                        <th scope="col">Date d'inscription</th>
                        <th scope="col">Établissement</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in data %}
                        <tr>
                            <td>
                                <a href="{{ path('app_inscription_edit', {id_sujet: sujet_id, id_insc: i.id}) }}">{{ i.prenom }} {{ i.nom }}</a>
                            </td>
                            <td> {{ i.email }} </td>
                            <td> {{ i.dateInsc|date('d/m/Y') }} </td>
                            <td> {{ i.etablissement }} </td>
                            <td><a href="{{ path('app_inscription_delete', {id: i.id}) }}" class="btn btn-danger">Supprimer</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}